
Truncate Table [dbo].[ServiceRequestDeletedReason]
Truncate Table [dbo].[Services]
Truncate Table [dbo].[ServiceSubscriptionTypes]
Truncate Table [dbo].[ServiceVehicleSubCategories]
Truncate Table [dbo].[VehicleDetails]
Truncate Table [dbo].[VehicleRequestedServices]
Truncate Table [dbo].[VehicleServicePrice]
Truncate Table  [dbo].[VehicleServiceTransactions]
Truncate Table  [dbo].[Wallet]
Truncate Table [dbo].[WalletTransactions]
Truncate Table [dbo].[WalletTransactionsTypes]